server:
  port: 8000
spring:
  datasource:    
    url: jdbc:mysql://localhost:3308/sales
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
         google:
          client-id: 
          client-secret: 
          scope:
           - email
           - profile